name: assignmentapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/jsons/
    - assets/images/
    - assets/svgs/


  fonts:
    - family: NotoSansKRBlack
      fonts:
        - asset: assets/fonts/noto_sans_kr_black.otf
    - family: NotoSansKRBold
      fonts:
        - asset: assets/fonts/noto_sans_kr_bold.otf
    - family: NotoSansKRLight
      fonts:
        - asset: assets/fonts/noto_sans_kr_light.otf
    - family: NotoSansKRMedium
      fonts:
        - asset: assets/fonts/noto_sans_kr_medium.otf
    - family: NotoSansKRRegular
      fonts:
        - asset: assets/fonts/noto_sans_kr_regular.otf
    - family: NotoSansKRThin
      fonts:
        - asset: assets/fonts/noto_sans_kr_thin.otf


